import * as THREE from '../../node_modules/three/build/three.module.js';

export const MISSION_ORDER = [
  {
    id: 'ayodhya',
    chapter: 'Ayodhya',
    title: 'The Eastern Gate',
    objective: 'Take the royal chariot through the eastern gate and leave Ayodhya behind.',
    marker: new THREE.Vector3(-90, 0, -8),
    spawn: new THREE.Vector3(-148, 0, -16),
    vehicleSpawn: new THREE.Vector3(-138, 0, -10),
    vehicleYaw: Math.PI / 2,
    radius: 14,
    requiresVehicle: true,
    intro: [
      "Dasharatha's capital still shines behind Rama.",
      'The exile begins on the road out of Ayodhya, not in a menu screen.',
    ],
    completion: 'The walls of Ayodhya fade behind the chariot. The forest now owns the road ahead.',
    enemies: [],
  },
  {
    id: 'forest',
    chapter: 'Forest Exile',
    title: 'Rakshasas in the Woods',
    objective: 'Reach the forest clearing and defeat the rakshasas threatening the exile camp.',
    marker: new THREE.Vector3(-26, 0, 54),
    spawn: new THREE.Vector3(-68, 0, 18),
    vehicleSpawn: new THREE.Vector3(-58, 0, 10),
    vehicleYaw: 0.48,
    radius: 15,
    intro: [
      'The road narrows into the forest and danger stops hiding.',
      'Rama must secure the camp before exile can become a life.',
    ],
    completion: 'The clearing is safe for a moment, but the exile is far from over.',
    enemies: [
      { type: 'rakshasa', position: [-12, 0, 60] },
      { type: 'rakshasa', position: [-30, 0, 68] },
      { type: 'rakshasa', position: [-44, 0, 50] },
    ],
  },
  {
    id: 'abduction',
    chapter: 'The Abduction',
    title: 'The Broken Camp',
    objective: 'Push deeper into the ruined grove and survive Ravana’s ambush.',
    marker: new THREE.Vector3(36, 0, 18),
    spawn: new THREE.Vector3(-6, 0, 46),
    vehicleSpawn: new THREE.Vector3(8, 0, 34),
    vehicleYaw: -0.18,
    radius: 15,
    intro: [
      'A false lure has drawn Rama away from camp.',
      'When he returns, the clearing is broken and the pursuit begins.',
    ],
    completion: 'Sita is gone. The forest is no longer a refuge but a trail to war.',
    enemies: [
      { type: 'rakshasa', position: [18, 0, 14] },
      { type: 'rakshasa', position: [32, 0, 32] },
      { type: 'guard', position: [52, 0, 16] },
    ],
  },
  {
    id: 'kishkindha',
    chapter: 'Kishkindha',
    title: 'Alliance on the Heights',
    objective: 'Climb into Kishkindha and defeat the challengers blocking Sugriva’s alliance.',
    marker: new THREE.Vector3(76, 0, -58),
    spawn: new THREE.Vector3(26, 0, 12),
    vehicleSpawn: new THREE.Vector3(18, 0, 2),
    vehicleYaw: -1.26,
    radius: 16,
    intro: [
      'In the rocky heights, grief finally meets help.',
      'Hanuman and Sugriva become allies only after strength is proven.',
    ],
    completion: 'The alliance is sealed. Lanka is no longer beyond reach.',
    enemies: [
      { type: 'guard', position: [60, 0, -42] },
      { type: 'guard', position: [78, 0, -64] },
      { type: 'brute', position: [92, 0, -56] },
    ],
  },
  {
    id: 'lanka',
    chapter: 'Lanka',
    title: 'Break the Outer City',
    objective: 'Cross into Lanka, breach the outer district, and clear Ravana’s defenders.',
    marker: new THREE.Vector3(132, 0, 44),
    spawn: new THREE.Vector3(82, 0, -46),
    vehicleSpawn: new THREE.Vector3(94, 0, -54),
    vehicleYaw: 0.92,
    radius: 17,
    intro: [
      'The sea has been crossed. Lanka rises ahead in red stone and fire.',
      'This is no corridor. You enter the enemy city from the street.',
    ],
    completion: 'The outer district falls. Ravana’s palace stands exposed.',
    enemies: [
      { type: 'guard', position: [116, 0, 34] },
      { type: 'guard', position: [128, 0, 58] },
      { type: 'guard', position: [142, 0, 40] },
      { type: 'rakshasa', position: [150, 0, 56] },
    ],
  },
  {
    id: 'ravana',
    chapter: 'War for Lanka',
    title: 'Ravana’s Last Court',
    objective: 'Advance into the throne court and defeat Ravana.',
    marker: new THREE.Vector3(158, 0, 114),
    spawn: new THREE.Vector3(126, 0, 42),
    vehicleSpawn: new THREE.Vector3(114, 0, 34),
    vehicleYaw: 1.58,
    radius: 18,
    intro: [
      'The final court opens ahead. Ravana waits at the heart of Lanka.',
      'This is the last fight between exile and homecoming.',
    ],
    completion: 'Ravana falls. The road now turns back toward Ayodhya and coronation.',
    enemies: [
      { type: 'guard', position: [144, 0, 100] },
      { type: 'guard', position: [168, 0, 100] },
      { type: 'rakshasa', position: [144, 0, 124] },
      { type: 'boss', position: [158, 0, 114] },
    ],
  },
];

export const INTRO_SCENE = [
  {
    speaker: 'Narrator',
    text: 'Ayodhya stood at the height of Dasharatha’s reign, radiant, ordered, and full of promise.',
  },
  {
    speaker: 'Dasharatha',
    text: 'Rama, the weight of an old vow now falls on this house. The crown must wait. Exile cannot.',
  },
  {
    speaker: 'Kaikeyi',
    text: 'The promise was mine to call, and the kingdom must now honor it.',
  },
  {
    speaker: 'Sita',
    text: 'If the road leads you into the wild, it leads me there as well.',
  },
  {
    speaker: 'Lakshmana',
    text: 'Ayodhya can keep its walls. My place is at your side.',
  },
  {
    speaker: 'Narrator',
    text: 'So the prince steps away from the throne and into the journey that will cross forests, kingdoms, and war.',
  },
];
